# Generated by Django 4.2.11 on 2024-04-23 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorialapp', '0002_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='roomnum',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subject',
            field=models.CharField(choices=[('English', 'English'), ('History', 'History'), ('Art', 'Art'), ('Music', 'Music'), ('Gym', 'Gym'), ('Math', 'Math'), ('Science', 'Science'), ('Elective', 'Elective')], max_length=200, null=True),
        ),
    ]
