# Generated by Django 4.2.11 on 2024-05-01 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorialapp', '0003_teacher_roomnum_alter_teacher_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='club',
            field=models.CharField(choices=[('none', 'none'), ('art', 'art'), ('photography', 'photography'), ('videogames', 'videogames'), ('woodworking', 'woodworking'), ('poetry', 'poetry'), ('debate', 'debate'), ('band', 'band'), ('robotics', 'robotics'), ('soccer', 'soccer'), ('chess', 'chess'), ('gardening', 'gardening'), ('theater', 'theater')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('M', 'M'), ('F', 'F'), ('NB', 'NB')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='club',
            field=models.CharField(choices=[('none', 'none'), ('art', 'art'), ('photography', 'photography'), ('videogames', 'videogames'), ('woodworking', 'woodworking'), ('poetry', 'poetry'), ('debate', 'debate'), ('band', 'band'), ('robotics', 'robotics'), ('soccer', 'soccer'), ('chess', 'chess'), ('gardening', 'gardening'), ('theater', 'theater')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='gender',
            field=models.CharField(choices=[('M', 'M'), ('F', 'F'), ('NB', 'NB')], max_length=200, null=True),
        ),
    ]
